### ISSUE TITLE
format yaml/json output flag

### ISSUE THREAD

**Issue by kfox1111** [anthonyharrison/sbomdiff#2]
Very interesting tool.

Could an output option be added to format the results into json or yaml so that further tools can be used to more easily process the output?

**Comment by anthonyharrison** [comment]
Hello @kfox1111 . Thanks for the suggestion. Will add it to my new features list.

**Comment by anthonyharrison** [comment]
> Hello @kfox1111 . Thanks for the suggestion. Will add it to my new features list.

@kfox1111 . Proposed diff record. Status will be one of change/add/renove. Is this OK?

```json
{
    "package": "my_package",
    "status": "change",
    "version": {
      "from": "2:2.99.917",
      "to": "2:2.99.918"
    },
    "license": {
      "from": "NOASSERTION",
      "to": "MIT"
    }
  },
```

**Comment by kfox1111** [comment]
Yeah, that looks great. :)

**Comment by anthonyharrison** [comment]
Feature added in release 0.5.0
